# Generated by Django 2.1.2 on 2018-10-25 18:35

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_image',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img/hero_image/'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_image',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='img/thumb_image/'),
        ),
    ]
