# Generated by Django 2.1.2 on 2018-10-25 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hero_image',
            field=models.ImageField(null=True, upload_to='media/img/'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumb_image',
            field=models.ImageField(null=True, upload_to='media/img/'),
        ),
    ]
